# Generated by Django 3.2.8 on 2021-11-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0002_auto_20211123_1001'),
        ('users', '0005_user_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='child',
        ),
        migrations.AddField(
            model_name='user',
            name='children',
            field=models.ManyToManyField(to='kindergarten.Child'),
        ),
    ]
