# Generated by Django 3.2.8 on 2021-11-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0003_auto_20211126_1305'),
        ('users', '0006_auto_20211123_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='children',
            field=models.ManyToManyField(blank=True, to='kindergarten.Child'),
        ),
    ]
