# Generated by Django 3.2.8 on 2021-12-01 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.DeleteModel(
            name='NewsFile',
        ),
    ]
