# Generated by Django 3.2.8 on 2021-12-01 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20211201_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='main_image',
            field=models.FileField(default='', null=True, upload_to='images/main'),
        ),
        migrations.CreateModel(
            name='NewsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='images/rest')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='content.news')),
            ],
        ),
    ]
