# Generated by Django 3.2.8 on 2021-12-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20211201_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='header',
            field=models.CharField(max_length=50),
        ),
    ]
