# Generated by Django 3.2.8 on 2021-12-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_news_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='files')),
                ('permission', models.CharField(choices=[('HEADMASTER', 'HEADMASTER'), ('TEACHER', 'TEACHER'), ('PARENT', 'PARENT')], default='HEADMASTER', max_length=255)),
            ],
        ),
    ]
