# Generated by Django 3.2.8 on 2021-12-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default='', null=True, upload_to='files'),
        ),
    ]
