# Generated by Django 3.2.8 on 2021-11-23 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('YOUNGERS', 'YOUNGERS'), ('MIDDLES', 'MIDDLES'), ('OLDERS', 'OLDERS')], default='YOUNGERS', max_length=255)),
                ('teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='M', max_length=10)),
                ('date_of_birth', models.DateField()),
                ('pesel', models.CharField(max_length=11)),
                ('eats_breakfast', models.BooleanField(default=False)),
                ('eats_dinner', models.BooleanField(default=False)),
                ('eats_supper', models.BooleanField(default=False)),
                ('street', models.CharField(max_length=50)),
                ('house_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('coming_hour', models.TimeField()),
                ('leaving_hour', models.TimeField()),
                ('sicknesses', models.TextField(max_length=200, null=True)),
                ('extra_info', models.TextField(max_length=200, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten.group')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hours', models.IntegerField(verbose_name='Hours in kindergarten')),
                ('info', models.TextField(max_length=200)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten.child')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_for_all', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten.group')),
            ],
        ),
    ]
