# Generated by Django 3.2.8 on 2021-11-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='extra_info',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='sicknesses',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
