# Generated by Django 3.2.8 on 2021-11-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0003_auto_20211126_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
