# Generated by Django 3.2.8 on 2021-11-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0004_auto_20211127_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
