# Generated by Django 3.2.8 on 2021-12-07 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0005_alter_announcement_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Child', 'verbose_name_plural': 'Children'},
        ),
        migrations.RemoveField(
            model_name='child',
            name='extra_info',
        ),
        migrations.AddField(
            model_name='child',
            name='authorized_person_one',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='authorized_person_two',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kindergarten.group'),
        ),
        migrations.AlterField(
            model_name='child',
            name='pesel',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='sicknesses',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
