# Generated by Django 3.2.8 on 2021-12-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0006_auto_20211207_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='additional_info',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
