# Generated by Django 3.2.8 on 2021-12-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0007_child_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='authorized_parent_one',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='child',
            name='authorized_parent_two',
            field=models.CharField(default='', max_length=50),
        ),
    ]
