# Generated by Django 3.2.8 on 2021-12-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0008_auto_20211207_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='authorized_parent_one',
            new_name='parent_one',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='authorized_parent_two',
            new_name='parent_two',
        ),
    ]
