# Generated by Django 3.2.8 on 2021-12-20 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kindergarten', '0010_alter_announcement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kindergarten.group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
